### ISSUE TITLE
Missing attribute "cast_dict_to_dataframe"

### ISSUE THREAD

**Issue by An-Death** [urigoren/ssh_decorator#2]
At line 157 if condition trying to get attribute cast_dict_to_dataframe.

`157:    if (type(ret)==dict) and self.cast_dict_to_dataframe:`

Not object or class have this attribute.
Maybe that should look like that?
      `getattr(self, cast_dict_to_dataframe, default=True)`
Or maybe you should append attrib?

**Comment by urigoren** [comment]
Fixed it, thank you very much !
