### ISSUE TITLE
Missmatch in Readme 

### ISSUE THREAD

**Issue by An-Death** [urigoren/ssh_decorator#3]
You should import class from module
`from ssh_decorate.ssh_connect import ssh_connect`

Then that line will be work:
`ssh=ssh_connect('user','password','server')`

In your example you importing module **ssh_connect**... Then you should write like this:
`ssh=ssh_connect.ssh_connect('user','password','server')`

It's not a big deal, but it's the face of package =)

**Comment by urigoren** [comment]
Thank you very much (again),
I fixed the __init__.py file, the package and readme should match now
