### ISSUE TITLE
ssh_connect.bash() doesn't work at all 

### ISSUE THREAD

**Issue by An-Death** [urigoren/ssh_decorator#8]
1) bash function get doc-string from input func and use it as command. if input func with out __doc__ or __doc__ is empty - bash function doesn't work at all  
2) bash function should be lazy

**Comment by urigoren** [comment]
`bash` function will be removed soon.
In the meanwhile, throwing an exception if docstring is empty.
Use `ssh>"ls"` instead.

Thank you !
BTW, I gave you collaborator right
