### ISSUE TITLE
poblem with python 2.7

### ISSUE THREAD

**Issue by memogharib** [urigoren/ssh_decorator#9]
dear , i have this issue below after installation 
![image](https://user-images.githubusercontent.com/15365816/38249861-6bbbc9f0-374d-11e8-8224-1e25f6882169.png)
![image](https://user-images.githubusercontent.com/15365816/38249876-78cf102a-374d-11e8-8509-70f3cc564310.png)

can you help me please

**Comment by urigoren** [comment]
Hi,
Thank you very much for posting the issue.
I have removed the type annotation, everything now should work in python2.7.
If you run `pip install ssh_decorate --upgrade` everything should work.
Sorry for the trouble.
Uri

**Comment by memogharib** [comment]
thanks so much :)
